# This is a basic workflow to Run UFT script via ALM by Actions

name: ALM_CI_Utility

# Controls when the workflow will run
on:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ALM_Test"
  ALM_Test:
    # The type of runner that the job will run on
    runs-on: Windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Chg Dir and Exec ALM Test
        run: |
          echo '::CD C:\CI_Utility\ADM-FT-ToolsLauncher-main\bin\Debug'
          echo "::.\FTToolsLauncher.exe -paramfile ALM_TestSet.mtb"
  
